#Standard message for commanding rover velocity

float32 l1 #speed of front right wheel (cm/s) - Does not calculate slip
float32 l2 #speed of back left wheel (cm/s)
float32 r1 #speed of right wheel (cm/s) - Does not calculate slip
float32 r2 #speed of back right wheel (cm/s)
int32 time_to_drive #time for the velocity to run at (ms) (includes accel but not deaccel ATM)
float32 accel #cm/s^2 acceleration value
float32 deaccel #cm/s^2 deacceleration value

---

bool success
