#goal
float32 linear_speed    #speed of rover in cm/s
float32 turning_radius  #turning radius desired (cm)
                        # + is L, 0 is in place, - is R, >1E6 is straight. if in place, + linspeed is L, -linspeed is R
float32 degrees_to_turn # relative angle to turn to (based on current heading).

---

#result
float32 new_heading     #new heading of rover

---

#feedback
float32 current_heading #in-transit heading of rover
