#goal
float32 linear_speed    #speed of rover in cm/s
float32 turning_radius  #turning radius desired (cm)
                        # + is L, 0 is in place, - is R, >1E6 is straight. if in place, + linspeed is L, -linspeed is R
int32 run_duration      #time rover is moving (ms)
int32 accel_deacel_duration     #equal deaccel and accel times (ms).

---

#result


---

#feedback
int32 ellapsedtime #time rover has been moving
