#goal
float32 linear_speed    #speed of rover in cm/s
float32 turning_radius  #turning radius desired (cm)
                        # + is L, 0 is in place, - is R, >1E6 is straight. if in place, + linspeed is L, -linspeed is R
int32 run_duration      #time rover is moving (ms)
int32 accel             #accel & deaccel rates (cm/s).
bool continuous         #will there be a command after this?

---

#result
float32 encdist #averaged distance of all 4 encoders (measured from command start)

---

#feedback
float32 currentdist #current averaged distance of all 4 encoders (measured from command start)
