um7:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    port: "/dev/ttyAMA0" #check on flat rosey ls /dev/ttyUSB* to identify correct port
    baud: 115200
    frame_id: "bno055"
    update_rate: 100
    variance_acc: [0.0, 0.0, 0.0]
    variance_angular_vel: [0.0, 0.0, 0.0]
    variance_orientation: [0.0, 0.0, 0.0]