<?xml version="1.0"?>
<!-- RoseyBot Robot Description File -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- properties for robot dimensions (in m)-->
    <xacro:property name="base_width" value="0.3"/>
    <xacro:property name="base_length" value="0.3"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.1"/>
    <xacro:property name="ride_height" value="0.1"/>

    <link name="base_link">
        <collision>
            <origin xyz="0 0 0" rpy= "0 0 0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="pink"/>
        </visual>
    </link>

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel_joint"/>
        <origin xyz="${base_length/2} ${base_width} ${ride_height}" rpy= "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name="left_front_wheel_link">
        <collision>
            <origin xyz="0 0 0" rpy= "0 0 0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="pink"/>
        </visual>
    </link>


</robot>